const {test}=require('node:test'),assert=require('node:assert/strict');const {defaults,validate,migrate,markdown,parse}=require('../core.cjs');
test('complete Markdown round trip preserves all fields, Unicode, fences, empty dates and settings',()=>{const s=defaults();s.settings={theme:'rose',opacity:65};s.entries['2026-09-20']={body:'## 标题\n```json\n数据\n```\n<!-- COLORBAR-DIARY-DATA-V3 -->',updatedAt:'2026-09-20T12:00:00Z',items:[{tagId:'health',value:'第一行\n第二行',rating:5,color:'#123456'}]};s.entries['2026-09-21']={body:'',items:[]};assert.deepEqual(validate(parse(markdown(s))),s);assert.deepEqual(parse(markdown(s).replace(/\n/g,'\r\n')),s);assert.match(markdown(s),/😄/);});
test('migration merges unmatched tags without losing source text or metadata and is idempotent',()=>{const s={version:1,tags:[{id:'a',name:'心情',parent:null,color:'#123456',active:true},{id:'b',name:'生活',parent:null,color:'#654321',active:true},{id:'h',name:'健康',parent:null,color:'#123456',active:true}],entries:{'2026-09-20':{body:'当天正文',items:[{tagId:'a',value:'开心',color:'#123456',brightness:95},{tagId:'b',value:'散步',color:'#654321'},{tagId:'h',value:'良好',color:'#123456'}]}}};const next=migrate(s);assert.equal(s.version,1);assert.equal(next.entries['2026-09-20'].items.length,2);const i=next.entries['2026-09-20'].items[0];assert.equal(i.tagId,'thoughts');assert.match(i.value,/开心/);assert.match(i.value,/散步/);assert.equal(i.legacyItems.length,2);assert.equal(next.entries['2026-09-20'].items[1].tagId,'health');assert.deepEqual(migrate(next),next);assert.deepEqual(parse(markdown(next)),next);});
test('reject invalid rating, hierarchy, date and damaged archives',()=>{const s=defaults();s.entries['2026-09-20']={body:'',items:[{tagId:'work',value:'',color:'#123456',rating:4}]};assert.throws(()=>validate(s));s.entries={};s.tags[0].parent='health';assert.throws(()=>validate(s));assert.throws(()=>parse('# old Markdown'));assert.throws(()=>parse(markdown(defaults()).slice(0,-10)));});

test('deleting a used parent preserves children, records and archived rating',()=>{const {deleteTagState}=require('../public/archive.js');const s=defaults();s.entries['2026-09-21']={body:'',items:[{tagId:'health',value:'身体好转',color:'#76b5a0',rating:4},{tagId:'thoughts',value:'原有碎碎念',color:'#bcb4d6'}]};const next=deleteTagState(s,'health','thoughts');validate(next);assert.equal(next.tags.find(t=>t.id==='knee').parent,null);assert.ok(!next.tags.some(t=>t.id==='health'));assert.match(next.entries['2026-09-21'].items[0].value,/原有碎碎念/);assert.match(next.entries['2026-09-21'].items[0].value,/身体好转/);assert.equal(next.tagDeletionHistory[0].entries['2026-09-21'].rating,4);assert.deepEqual(parse(markdown(next)),next);assert.ok(s.tags.some(t=>t.id==='health'));});
test('deletion rejects child name conflicts without changing source',()=>{const {deleteTagState}=require('../public/archive.js');const s=defaults();s.tags.push({id:'another-knee',name:'膝盖',parent:null,color:'#123456',active:true});const before=structuredClone(s);assert.throws(()=>deleteTagState(s,'health','thoughts'),/重名/);assert.deepEqual(s,before);});

test('empty drafts do not retain blank bars; ratings and legacy color-only records survive',()=>{const s=defaults();s.entries['2026-09-21']={body:'',items:[{tagId:'thoughts',color:'#bcb4d6',value:'\n\n',records:[{id:'a',text:''},{id:'b',text:''}]},{tagId:'health',color:'#76b5a0',value:'',rating:4,records:[]},{tagId:'work',color:'#849bda',value:'保留\n\n',records:[{id:'c',text:'保留'},{id:'d',text:''}]},{tagId:'family',color:'#123456',value:''}]};const next=migrate(s);assert.ok(!next.entries['2026-09-21'].items.some(i=>i.tagId==='thoughts'));assert.equal(next.entries['2026-09-21'].items.find(i=>i.tagId==='work').value,'保留');assert.equal(next.entries['2026-09-21'].items.find(i=>i.tagId==='health').rating,4);assert.ok(next.entries['2026-09-21'].items.some(i=>i.tagId==='family'));assert.deepEqual(migrate(next),next);});

test('one reminder per day survives Markdown and migration without text; rejects malformed time',()=>{const s=defaults();s.entries['2026-09-30']={body:'',items:[],reminder:{id:'alarm-test',title:'项目会议',at:'2026-09-30T01:00:00.000Z',sound:'chime'}};validate(s);assert.deepEqual(parse(markdown(s)),s);assert.deepEqual(migrate(s),s);assert.match(markdown(s),/日程提醒/);s.entries['2026-09-30'].reminder.at='invalid';assert.throws(()=>validate(s),/提醒/);});

test('standalone v4 opens an empty diary; rejects newer formats and unclosed record fences',()=>{const {importFile,readView}=require('../core.cjs');const empty=defaults();assert.deepEqual(importFile(markdown(empty)).state,empty);assert.throws(()=>importFile(markdown(empty).replace('导出格式版本：4','导出格式版本：5')),/升级/);assert.throws(()=>readView('## 2026-09-26\n### 碎碎念\n```markdown\n未闭合'),/未闭合/);const partial=importFile('## 2026-09-26\n### 碎碎念\n```markdown\n最后一条\n```',empty);assert.equal(partial.state.entries['2026-09-26'].items[0].value,'最后一条');});
